
services:
  web:
    build: .
    volumes:
      - .:/app
    container_name: drf_finance_bknd
    command: gunicorn finance.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env

