# Generated by Django 6.0.4 on 2026-05-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsmodel',
            name='category',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('rent', 'Rent'), ('food', 'Food')], null=True),
        ),
    ]
